// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ3otqfYzKhVOwJupcKmB5VnuyOu_W-to',
    appId: '1:725499738773:web:4c0f254909debddd50799c',
    messagingSenderId: '725499738773',
    projectId: 'deshi-app-85ebe',
    authDomain: 'deshi-app-85ebe.firebaseapp.com',
    storageBucket: 'deshi-app-85ebe.appspot.com',
    measurementId: 'G-7PVX8XCYRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhXuhodoOiumiQfG5T_QPCwHtfItPeAZA',
    appId: '1:725499738773:android:d88f485f241e90e750799c',
    messagingSenderId: '725499738773',
    projectId: 'deshi-app-85ebe',
    storageBucket: 'deshi-app-85ebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTqd753ThEDWAjfGc7XWZwvuRXnokLoQU',
    appId: '1:725499738773:ios:07e410882ac5660e50799c',
    messagingSenderId: '725499738773',
    projectId: 'deshi-app-85ebe',
    storageBucket: 'deshi-app-85ebe.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTqd753ThEDWAjfGc7XWZwvuRXnokLoQU',
    appId: '1:725499738773:ios:07e410882ac5660e50799c',
    messagingSenderId: '725499738773',
    projectId: 'deshi-app-85ebe',
    storageBucket: 'deshi-app-85ebe.appspot.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ3otqfYzKhVOwJupcKmB5VnuyOu_W-to',
    appId: '1:725499738773:web:cd2bc9a09acfa50150799c',
    messagingSenderId: '725499738773',
    projectId: 'deshi-app-85ebe',
    authDomain: 'deshi-app-85ebe.firebaseapp.com',
    storageBucket: 'deshi-app-85ebe.appspot.com',
    measurementId: 'G-VY6SK4KKQB',
  );
}
